### ISSUE TITLE
Всё-таки, возможно ли добавка MQTT протокола в прошивку?

### ISSUE THREAD

**Issue by itProfi** [vad7/PowerMeter-IrDA#1]
Добрый день! Всё-таки, хочется повторить вопрос..Возможно ли внедрение MQTT протокола в вашу прошивку. ThingSpeak - это удобно, но не для всех и труднее оперировать с получаемыми данными..)

**Comment by edgiru** [comment]
проект интересный конечно. про mqtt актуально. возможно автору просто не нужен этот функционал, а по чьей то просьбе наверно добавлять не будет.

**Comment by vad7** [comment]
Добрый день!
Мне MQTT не интересен, а доработка требует времени, которое как-то должно быть скомпенсировано.

**Comment by itProfi** [comment]
Озвучьте, пожалуйста, компенсацию..

**Comment by vad7** [comment]
Зависит от ТЗ, если реально интересует: v1708800-4@yahoo.com
