### ISSUE TITLE
Потрясающе!!!

### ISSUE THREAD

**Issue by sergeimonakhov** [vad7/PowerMeter-IrDA#2]
А не подскажите что нужно из хардварной части, чтобы все это собрать и запустить

**Comment by vad7** [comment]
http://vad-7.blogspot.ru/2017/03/mercury231.html

**Comment by sergeimonakhov** [comment]
Да я видел Ваш блог, но я совсем не силен в электротехнике :( Буду искать кто поможет, спасибо

**Comment by vad7** [comment]
Все это паяется на коленке, нужны - платка ESP-12E/F, TFDU4100, FM24W256 (плюс адаптер SOIC8 - DIP8), БП HLK-PM03, резисторы с конденсаторами и обычная макетная плата. Все это есть на али.

**Comment by sergeimonakhov** [comment]
ага, спасибо огромное! а еще по поводу wi-fi, как потом подключение осуществляется? я так понимаю я это устройство конекчу к своей сети каким то способом?

**Comment by vad7** [comment]
Сама esp8266 подключается к заданному роутеру. Можно и к самой esp8266 коннектиться по wi-fi. 
В меню поиск wi-fi точек и подключение по клику есть.

**Comment by ARJV** [comment]
Добрый день! немного затупил и за место платы чистой ESP8266 взял nodemcu v3. На ней можно реализовать, и нужно что либо менять тогда в схеме?

**Comment by vad7** [comment]
Добрый!
Эта плата только для отладки подойдет. Например, моя nodemcu виснет при подачи питания (из-за хардварного двойного сброса) - приходится вручную ресет давить.

**Comment by sergeimonakhov** [comment]
![2017-12-02 11 52 06](https://user-images.githubusercontent.com/4964525/33513623-70310b86-d757-11e7-9a82-5e7bd4c2e948.jpg)
Собрали плату по первой схеме, подскажите как теперь прошивку залить, я так понимаю надо по com порту цеплятся

**Comment by vad7** [comment]
Первоначальная прошивка esp8266 стандартная - по проводам через USB-TTL UART конвертер, который поддерживает 3.3V.
Через esp flash download tool прошивать firmware.bin по адресу 0x00000.
Дальше уже можно зайти на esp8266 по wifi и залить webfiles.bin.
Соединять TXD-RX, RXD-ТХ с конвертером.
IO0 кнопкой через резистор 100 Ом на землю при включении для входа в режим прошивки.

**Comment by ARJV** [comment]
Прошил, появилась сеть ESP8266. Всё верно? но она требует пароль.

**Comment by vad7** [comment]
По умолчанию: 0123456789

**Comment by sergeimonakhov** [comment]
Спасибо! наконец то запустил это дело
